name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js site
        run: |
          # Set NODE_ENV to production for proper basePath
          export NODE_ENV=production
          npm run build
          
          # Create out directory structure
          mkdir -p out
          
          # Copy all HTML files and folders from .next/server/app
          cp -r .next/server/app/* out/ 2>/dev/null || true
          
          # Create _next directory structure
          mkdir -p out/_next/static
          
          # Copy static assets (CSS, JS, media)
          cp -r .next/static/* out/_next/static/ 2>/dev/null || true
          
          # Copy public directory contents to root of out
          cp -r public/* out/ 2>/dev/null || true
          
          # Create .nojekyll file to prevent GitHub Pages from ignoring _next
          touch out/.nojekyll
          
          # Fix asset paths for GitHub Pages
          node scripts/fix-asset-paths.js
          
          # Debug: List contents
          echo "Contents of out directory:"
          ls -la out/
          echo "Checking paths in index.html:"
          grep -o 'href="/WeatherShield-Website/_next' out/index.html | head -3 || echo "Paths not found"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4